FROM python:3.8

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./data-provider /app

CMD [ "uvicorn", "app.data-provider.main:covid_app", "--reload", "--host", "0.0.0.0", "--port", "5000" ]